name: pkg2chart CI

on:
  push:
    branches: [main]
    paths:
      - "pkg2chart/**"
  pull_request:
    branches: [main]
    paths:
      - "pkg2chart/**"

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pkg2chart

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: ./pkg2chart/go.mod

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          working-directory: ./pkg2chart

      - name: Run tests
        run: go test -v ./...
